- type: job
  id: TechnicalAssistant
  name: job-name-technical-assistant
  description: job-description-technical-assistant
  playTimeTracker: JobTechnicalAssistant
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 3600 #1 hr
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 18000 #5 hrs
      inverted: true # stop playing intern if you're good at engineering!
  startingGear: TechnicalAssistantGear
  icon: "JobIconTechnicalAssistant"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: TechnicalAssistantGear
  equipment:
    id: TechnicalAssistantPDA
    pocket2: BookEngineersHandbook

- type: chameleonOutfit
  id: TechnicalAssistantChameleonOutfit
  job: TechnicalAssistant
  equipment:
    head: ClothingHeadHatHardhatOrange
    eyes: ClothingEyesGlassesMeson
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterVestHazard
    gloves: ClothingHandsGlovesColorYellow
