- type: department
  id: Cargo
  name: department-Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  - Pilot # Scav

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Bartender # Frontier
  - Botanist # Frontier
  # - Boxer # Frontier
  # - Chaplain # Frontier
  - Chef # Frontier
  # - Clown # Frontier
  - HeadOfPersonnel # Frontier
  - Janitor # Scav
  # - Lawyer # Frontier
  # - Librarian # Frontier
  # - Mime # Frontier
  # - Musician # Frontier
  # - Passenger # Frontier
  # - Reporter # Frontier
  # - Visitor # Frontier
  # - Zookeeper # Frontier
  # - ServiceWorker # Frontier
  # - Contractor # Frontier # Scav
  # - Mercenary # Frontier # Scav
  - Borg # Frontier

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description # Frontier
  color: "#0c344d"
  roles:
  - CentralCommandOfficial
#  - CBURN # Frontier
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
#  - DeathSquad # Frontier
  - ERTMailCarrier # Frontier
  editorHidden: true
  weight: 120

- type: department
  id: Command
  name: department-Command
  description: department-Command-description # Frontier
  color: "#334E6D"
  roles:
  - Captain
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  # - HeadOfSecurity # Scav
  - ChiefTacticalOfficer # Scav
  - ResearchDirector
  - Quartermaster
  # - CentralCommandOfficial # Frontier
  # - CBURN # Frontier
  # - ERTLeader # Frontier
  # - ERTChaplain # Frontier
  # - ERTJanitor # Frontier
  # - ERTMedical # Frontier
  # - ERTSecurity # Frontier
  # - ERTEngineer # Frontier
  # - DeathSquad # Frontier
  # - StationRepresentative # Frontier #Scav
  # - Sheriff # Frontier #Scav
  # - PlantManager # Frontier #Scav
  # - StationTrafficController # Frontier #Scav
  primary: false
  weight: 100

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician # Frontier
  - ChiefEngineer # Frontier
  - StationEngineer # Frontier
  - TechnicalAssistant # Frontier
  # - PlantManager # Frontier #Scav
  # - PlantTechnician # Frontier #Scav

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic

- type: department
  id: Security
  name: department-Security
  description: department-NFSecurity-description # Frontier
  color: "#5C7D4D" # Frontier: DE3A3A<5C7D4D
  weight: 1 # Frontier: 20<1 - accounted for in jobs
  roles:
#  - Detective # Frontier
#  - HeadOfSecurity # Frontier
#  - SecurityCadet # Frontier
#  - SecurityOfficer # Frontier
#  - Warden # Frontier
  - PrisonGuard ##nyano
  - Brigmedic # Frontier
#  - SecurityGuard # Frontier
  - NFDetective # Frontier
  - Cadet # Frontier
  - Deputy # Frontier
  - Bailiff # Frontier
  - Sheriff # Frontier
  - SeniorOfficer # Frontier
  - PublicAffairsLiaison # Frontier
  editorHidden: true # Scav

- type: department
  id: Science
  name: department-Science
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - Scientist
  - ResearchAssistant

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#D381C9"
  roles:
  - Borg
  - StationAi

- type: department
  id: Specific
  name: department-Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: 10
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist
  primary: false
  editorHidden: true # Frontier
