using System.Collections.Generic;
using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Scav.Cargo;
using Content.Shared.Cargo.Components;
using Content.Shared.Cargo.Prototypes;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Scav.Cargo.UI;

[GenerateTypedNameReferences]
public sealed partial class FundManagementConsoleMenu : FancyWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly EntityQuery<StationBankAccountComponent> _bankQuery;

    public event Action<Dictionary<ProtoId<CargoAccountPrototype>, int>, double, double>? OnAllocationSave;
    public event Action<ProtoId<CargoAccountPrototype>?, int, ProtoId<CargoAccountPrototype>?>? OnWithdraw;
    public event Action<ProtoId<CargoAccountPrototype>?>? OnDeposit;

    private EntityUid? _station;
    private Dictionary<ProtoId<CargoAccountPrototype>, int> _accounts = new();
    private ProtoId<CargoAccountPrototype> _selectedAccount = "";

    private int _withdrawalAmount;

    private bool _allowPrimaryAccountAllocation;
    private bool _allowPrimaryCutAdjustment;
    private bool _lockboxCutEnabled;

    private double _primaryCut;
    private double _lockboxCut;

    private readonly HashSet<Control> _addedControls = new();
    private readonly List<SpinBox> _spinBoxes = new();
    private readonly Dictionary<ProtoId<CargoAccountPrototype>, RichTextLabel> _balanceLabels = new();

    public FundManagementConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _bankQuery = _entityManager.GetEntityQuery<StationBankAccountComponent>();

        TabContainer.SetTabTitle(0, Loc.GetString("cargo-console-menu-tab-title-funds"));
        TabContainer.SetTabTitle(1, Loc.GetString("cargo-console-menu-tab-title-funds"));

        AccountSelection.OnItemSelected += args =>
        {
            AccountSelection.SelectId(args.Id);
            if (AccountSelection.SelectedMetadata is ProtoId<CargoAccountPrototype> selectedAccount)
                _selectedAccount = selectedAccount;
            BuildTransferTab();
        };

        WithdrawAmount.IsValid = val =>
        {
            if (_accounts is not {Count: > 0})
                return true;

            return WithdrawAmountValid(val);
        };

        WithdrawAmount.ValueChanged += args =>
        {
            _withdrawalAmount = args.Value;
        };

        WithdrawOptions.OnItemSelected += idx =>
        {
            WithdrawOptions.SelectId(idx.Id);
        };

        WithdrawButton.OnPressed += _ =>
        {
            var otherAccount = WithdrawOptions.SelectedMetadata is ProtoId<CargoAccountPrototype> selectedAccount
                ? selectedAccount
                : (ProtoId<CargoAccountPrototype>?)null;

            OnWithdraw?.Invoke(_selectedAccount, _withdrawalAmount, otherAccount);
        };

        DepositButton.OnPressed += _ =>
        {
            OnDeposit?.Invoke(_selectedAccount);
        };

        PrimaryCut.ValueChanged += args =>
        {
            _primaryCut = (double)args.Value / 100.0;
            UpdateAllocationSaveButtonDisabled();
        };

        LockboxCut.ValueChanged += args =>
        {
            _lockboxCut = 1.0 - (double)args.Value / 100.0;
            UpdateAllocationSaveButtonDisabled();
        };

        SaveButton.OnPressed += _ =>
        {
            var accounts = _accounts.OrderBy(p => p.Key).Select(p => p.Key).ToList();
            var dicts = new Dictionary<ProtoId<CargoAccountPrototype>, int>();
            for (var i = 0; i< accounts.Count; i++)
            {
                dicts.Add(accounts[i], _spinBoxes[i].Value);
            }

            OnAllocationSave?.Invoke(dicts, _primaryCut, _lockboxCut);
            SaveButton.Disabled = true;
        };

        _cfg.OnValueChanged(CCVars.AllowPrimaryCutAdjustment, enabled => { _allowPrimaryCutAdjustment = enabled; }, true);
        _cfg.OnValueChanged(CCVars.LockboxCutEnabled, enabled => { _lockboxCutEnabled = enabled; }, true);

        BuildAccountList();
        BuildTransferTab();
        BuildAllocationTab();
    }

    private bool WithdrawAmountValid(int val)
    {
        if (!_accounts.TryGetValue(_selectedAccount, out var account))
            return false;

        return val >= 0 && val <= account;
    }

    private void BuildAllocationTab()
    {
        if (!_entityManager.TryGetComponent<StationBankAccountComponent>(_station, out var bank))
            return;

        if (_allowPrimaryCutAdjustment)
        {
            HelpLabel.Text = Loc.GetString("cargo-funding-alloc-console-label-help-adjustible");
        }
        else
        {
            HelpLabel.Text = Loc.GetString("cargo-funding-alloc-console-label-help-non-adjustible",
                ("percent", (int) (bank.PrimaryCut * 100)));
        }

        foreach (var ctrl in _addedControls)
        {
            ctrl.Orphan();
        }

        _addedControls.Clear();
        _spinBoxes.Clear();
        _balanceLabels.Clear();

        _primaryCut = bank.PrimaryCut;
        _lockboxCut = bank.LockboxCut;

        LockboxCut.OverrideValue(100 - (int)(_lockboxCut * 100));
        PrimaryCut.OverrideValue((int)(_primaryCut * 100));

        LockboxCut.IsValid = val => val is >= 0 and <= 100;
        PrimaryCut.IsValid = val => val is >= 0 and <= 100;

        LockboxCut.Visible = _lockboxCutEnabled;
        LockboxCutLabel.Visible = _lockboxCutEnabled;
        PrimaryCut.Visible = _allowPrimaryCutAdjustment;
        PrimaryCutLabel.Visible = _allowPrimaryCutAdjustment;

        foreach (var (account, balance) in _accounts.OrderBy(p => p.Key))
        {
            var accountProto = _prototypeManager.Index(account);

            var accountNameLabel = new RichTextLabel
            {
                Modulate = accountProto.Color,
                Margin = new Thickness(0, 0, 10, 0)
            };
            accountNameLabel.SetMarkup($"[bold]{Loc.GetString(accountProto.Name)}[/bold]");
            EntriesContainer.AddChild(accountNameLabel);

            var codeLabel = new RichTextLabel
            {
                Text = $"[font=\"Monospace\"]{Loc.GetString(accountProto.Code)}[/font]",
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(5, 0),
            };
            EntriesContainer.AddChild(codeLabel);

            var balanceLabel = new RichTextLabel
            {
                Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", balance)),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(5, 0),
            };
            EntriesContainer.AddChild(balanceLabel);

            var box = new SpinBox
            {
                HorizontalAlignment = HAlignment.Center,
                HorizontalExpand = true,
                Value = (int) (bank.RevenueDistribution[account] * 100),
                IsValid = val => val is >= 0 and <= 100,
            };
            box.ValueChanged += _ => UpdateAllocationSaveButtonDisabled();
            EntriesContainer.AddChild(box);

            _spinBoxes.Add(box);
            _balanceLabels.Add(account, balanceLabel);
            _addedControls.Add(accountNameLabel);
            _addedControls.Add(codeLabel);
            _addedControls.Add(balanceLabel);
            _addedControls.Add(box);

        }
    }

    private void UpdateAllocationSaveButtonDisabled()
    {
        if (!_entityManager.TryGetComponent<StationBankAccountComponent>(_station, out var bank))
            return;

        var sum = _spinBoxes.Sum(s => s.Value);
        var incorrectSum = sum != 100;

        var differs = false;
        var accounts = _accounts.OrderBy(p => p.Key).Select(p => p.Key).ToList();
        for (var i = 0; i < accounts.Count; i++)
        {
            var percent = _spinBoxes[i].Value;
            if (percent != (int) Math.Round(bank.RevenueDistribution[accounts[i]] * 100))
            {
                differs = true;
                break;
            }
        }
        differs = differs || _primaryCut != bank.PrimaryCut || _lockboxCut != bank.LockboxCut;

        SaveButton.Disabled = !differs || incorrectSum;

        var diff = sum - 100;
        SaveAlertLabel.Visible = incorrectSum;
        SaveAlertLabel.SetMarkup(Loc.GetString("cargo-funding-alloc-console-label-save-fail",
            ("pos", Math.Sign(diff)),
            ("val", Math.Abs(diff))));
    }

    private void BuildAccountList()
    {
        var index = 0;
        AccountSelection.Clear();
        var accountSelectionValid = false;
        foreach (var (account, _) in _accounts.OrderBy(p => p.Key))
        {
            var accountProto = _prototypeManager.Index(account);
            AccountSelection.AddItem(Loc.GetString(accountProto.Name), index);
            AccountSelection.SetItemMetadata(index, account);


            if (_selectedAccount == account)
                accountSelectionValid = true;
            index++;
        }

        if (AccountSelection.ItemCount == 0)
        {
            AccountSelection.AddItem(Loc.GetString("cargo-console-menu-account-selection-item-no-account"));
        }

        if ((!accountSelectionValid) || _selectedAccount == "")
        {
            AccountSelection.Select(0);
            if (AccountSelection.SelectedMetadata is ProtoId<CargoAccountPrototype> newSelected) //probably want to check if its still int eh list but oh well
                _selectedAccount = newSelected;
        }
    }
    private void BuildTransferTab()
    {
        var index = 0;
        WithdrawOptions.Clear();
        WithdrawOptions.AddItem(Loc.GetString("cargo-console-menu-account-action-option-withdraw"), index);
        index++;
        foreach (var (account, _) in _accounts.OrderBy(p => p.Key))
        {
            if (account != _selectedAccount)
            {
                var accountProto = _prototypeManager.Index(account);
                WithdrawOptions.AddItem(Loc.GetString("cargo-console-menu-account-action-option-transfer",
                        ("code", Loc.GetString(accountProto.Code))),
                    index);
                WithdrawOptions.SetItemMetadata(index, account);
                index++;
            }
        }

        BalanceLabel.Text = _accounts.TryGetValue(_selectedAccount, out var selectedAccount) ? Loc.GetString("cargo-console-menu-points-amount", ("amount", selectedAccount)) : Loc.GetString("bank-atm-menu-no-bank");
    }

    public void Update(FundManagementConsoleBuiState state)
    {
        _station = _entityManager.GetEntity(state.Station);
        _accounts = _entityManager.TryGetComponent<StationBankAccountComponent>(_station, out var bank) ? bank.Accounts : new Dictionary<ProtoId<CargoAccountPrototype>, int>();

        BuildAccountList();
        BuildTransferTab();
        BuildAllocationTab();
        UpdateAllocationSaveButtonDisabled();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_bankQuery.TryComp(_station, out var bankAccount))
            return;

        foreach (var (account, label) in _balanceLabels)
        {
            label.Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", bankAccount.Accounts[account]));
        }
    }
}
