using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Scav.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipRow : PanelContainer
{
    public Guid ShipId;
    public ShipRow()
    {
        RobustXamlLoader.Load(this);
    }
}
