using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Scav.Lobby.UI.Roles;

/// <summary>
/// A generic locking selector.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ProfileJobRow : BoxContainer
{
    [Dependency] private readonly SpriteSystem _spriteSystem = default!;

    private readonly SpriteSpecifier _unlockedIcon = new SpriteSpecifier.Rsi(new ResPath("/Textures/Interface/VerbIcons/lock.svg.192dpi.png"), "Unknown");
    private readonly SpriteSpecifier _lockedIcon = new SpriteSpecifier.Rsi(new ResPath("/Textures/Interface/VerbIcons/lock-red.svg.192dpi.png"), "Unknown");

    public ProfileJobRow(
        string title,
        int titleSize,
        string? description,
        TextureRect? icon = null,
        bool locked = true,
        FormattedMessage? unlockRequirements = null
    )
    {
        RobustXamlLoader.Load(this);

        TitleLabel.Text = title;
        TitleLabel.MinSize = new Vector2(titleSize, 0f);
        TitleLabel.ToolTip = description;

        if (icon != null)
        {
            AddChild(icon);
            icon.SetPositionFirst();
        }

        LockIcon.Visible = !locked;

        if (unlockRequirements != null)
        {
            var tooltip = new Tooltip();
            tooltip.SetMessage(unlockRequirements);
            LockIcon.TooltipSupplier = _ => tooltip;
        }
    }
}
